### ISSUE TITLE
There was an error when I installed Fairseq

### ISSUE THREAD

**Issue by yyz845935161** [facebookresearch/textlesslib#10]
When I use
pip install 
git+git://github.com:pytorch/fairseq.git@dd106d9534b22e7db859a6b87ffd7780c38341f8
Command, there is a 400 error, maybe the version of the problem，  resulting in unusable

**Comment by JadeCopet** [comment]
You could try using `pip install git+https://github.com/pytorch/fairseq@dd106d9534b22e7db859a6b87ffd7780c38341f8` ?

**Comment by LeyuanQu** [comment]
@JadeCopet 
Hello JadeCopet,
this command still not work.

Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/
Collecting git+https://github.com/pytorch/fairseq@dd106d9534b22e7db859a6b87ffd7780c38341f8
  Cloning https://github.com/pytorch/fairseq (to revision dd106d9534b22e7db859a6b87ffd7780c38341f8) to /tmp/pip-req-build-tg5wfu1a
  Running command git clone -q https://github.com/pytorch/fairseq /tmp/pip-req-build-tg5wfu1a

  Running command git rev-parse -q --verify 'sha^dd106d9534b22e7db859a6b87ffd7780c38341f8'
  Running command git fetch -q https://github.com/pytorch/fairseq dd106d9534b22e7db859a6b87ffd7780c38341f8
  Running command git checkout -q dd106d9534b22e7db859a6b87ffd7780c38341f8
  Resolved https://github.com/pytorch/fairseq to commit dd106d9534b22e7db859a6b87ffd7780c38341f8
  Running command git submodule update --init --recursive -q
  fatal: unable to access 'https://github.com/ngoyal2707/Megatron-LM/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
  Fetched in submodule path 'fairseq/model_parallel/megatron', but it did not contain adb23324c222aad0aad89308e70302d996a5eaeb. Direct fetching of that commit failed.

**Comment by WillQuCD** [comment]
Hi guys,
finally, this link works.

pip install git+https://github.com/pytorch/fairseq.git@dd106d9534b22e7db859a6b87ffd7780c38341f

**Comment by JadeCopet** [comment]
Considering this as solved. Thanks!
