### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by Rongjiehuang** [facebookresearch/textlesslib#13]
Hi author,
           Thanks for your inspiring work. I read your paper titled _Generative Spoken Dialogue Language Modeling_ recently, and wonder if you could release the corresponding code. Thanks in advance.

Best

**Comment by eugene-kharitonov** [comment]
Hello,

Please find it here https://github.com/pytorch/fairseq/tree/main/examples/textless_nlp/gslm

**Comment by Rongjiehuang** [comment]
> Hello,
> 
> Please find it here https://github.com/pytorch/fairseq/tree/main/examples/textless_nlp/gslm

Hello, I find that this repo is the code of _Generative Spoken Language Modeling_ rather than _Generative Spoken Dialogue Language Modeling_

**Comment by adiyoss** [comment]
Hi @Rongjiehuang,
You are right, we did not release the code for the Generative Spoken Dialogue Language Modeling yet. 
We are working on it, and we will release it soon

**Comment by Rongjiehuang** [comment]
> Hi @Rongjiehuang, You are right, we did not release the code for the Generative Spoken Dialogue Language Modeling yet. We are working on it, and we will release it soon

Thanks again for your inspiring work, and looking forward to the code release!
