### ISSUE TITLE
Any possibility to train/finetune HuBert using custom data

### ISSUE THREAD

**Issue by KingStorm** [facebookresearch/textlesslib#9]
This is really great job! I am wondering if textlesslib could also support training or finetuning HuBert with custom data. 

For example not just in English but other language data.

**Comment by JadeCopet** [comment]
Hello, 

Thanks for your interest! 

Training or fine-tuning of HuBERT in textlesslib is not planned at the moment. Please refer to fairseq's codebase to do so: https://github.com/pytorch/fairseq/tree/main/examples/hubert

**Comment by KingStorm** [comment]
Sure, thanks.
